# Indicate active profile for the application
spring.profiles.active=dev

spring.application.name=platzi-play
# Indicate context path for the application
server.servlet.context-path=/platzi-play/api

# PostgreSQL database configuration
spring.datasource.driver-class-name=org.postgresql.Driver

#Langchain4j -> allows integration with AI
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

# Configuración específica para que Swagger encuentre el path correcto
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
