server.port=9092


# Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d7mf2ge7r5hc7385p8g0-a:5432/platzi_play_db_jxaz
spring.datasource.username=elder
spring.datasource.password=swdJkrDXE9QskhbaO0xcia5wSWTRhWaz

# Properties for JPA and Hibernate
spring.jpa.hibernate.ddl-auto=update

#Langchain4j -> allows integration with AI
langchain4j.open-ai.chat-model.api-key=demo
